var request = require('request');

/**Verify Your NNumber For Signup
 * @param {number} phone - usernumber formated as +234 9012345678
 * @param {number} accNO  - 11 digits used and generated by system
 * @param {string} bankName  - Bank Housing The Account
 */
exports.getAccount = (phone,accNo,bankName)=>{
    var options = {
    'method': 'POST',
    'url': 'https://fsi.ng/api/v1/africastalking/version1/messaging',
    'headers': {
        'sandbox-key': '4NutTmCmg6PqSbvqIvqDcBGXIA6ImPQs1648949642',
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({
        "username": "sandbox",
        "to": phone,
        "message": `Your Account Number is ${accNo} \n Bank is : ${bankName}`
    })

    };
    request(options, function (error, response) {
        if(error){
            console.log(error);
        }
    });

}