var request = require('request');

/**Verify Your NNumber For Signup
 * @param {string} phone - usernumber formated as +234 9012345678
 * @param {number} code  - 4 digits used and generated by system
 */
exports.verifySms = (phone,code)=>{
    var options = {
    'method': 'POST',
    'url': 'https://fsi.ng/api/v1/africastalking/version1/messaging',
    'headers': {
        'sandbox-key': '4NutTmCmg6PqSbvqIvqDcBGXIA6ImPQs1648949642',
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({
        "username": "sandbox",
        "to": phone,
        "message": `Your Verification Code is ${code} \n if you didnt request this ignore the message`
    })

    };
    request(options, function (error, response) {
    if (error) throw new Error(error);
    console.log(response.body);
    });

}